export const REDUNDANT_PHRASES = new Map<string, string>([
  ["in order to", "to"],
  ["due to the fact that", "because"],
  ["at this point in time", "now"],
  ["in the event that", "if"],
  ["for the purpose of", "for"],
  ["with regard to", "about"],
  ["in relation to", "about"],
  ["as a matter of fact", ""],
  ["it is important to note that", ""],
  ["it should be noted that", ""],
  ["please note that", ""],
  ["keep in mind that", ""],
  ["bear in mind that", ""],
  ["take into consideration", "consider"],
  ["make use of", "use"],
  ["give consideration to", "consider"],
  ["come to the conclusion", "conclude"],
  ["reach a decision", "decide"],
  ["make a recommendation", "recommend"],
  ["conduct an analysis", "analyze"],
  ["perform an evaluation", "evaluate"],
  ["carry out an investigation", "investigate"],
  ["at the present time", "now"],
  ["in the near future", "soon"],
  ["on a regular basis", "regularly"],
  ["first and foremost", "first"],
  ["last but not least", "finally"],
  ["each and every", "every"],
  ["null and void", "void"],
  ["safe and sound", "safe"],
]);
